version: "3"
services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: http://localhost:3000
      APP_SECRET: 4das4d87zxcvx-asd*+sad1zxcasd03--=
      DATABASE_URL: postgresql://docmost:1-zxcvasd123-ascxvcvkdd-1@db:5432/docmost?schema=public
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./docmost:/app/data/storage
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: 1-zxcvasd123-ascxvcvkdd-1
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis_data:/data
volumes:
  docmost: null
  db_data: null
  redis_data: null
networks: {}
